riemann/riemann-tools

bin/riemann-dir-space
this can be useful if/when you want to ensure a specific directory
doesn't go over a certain size, or if you want to monitor a particular
directory's size.
I use it in production to monitor a few key directories, (with no
alerts), and when disk space is critical I use `coalesce` (with these
metrics and the riemann health disk space metric) to get an alert
description that includes the space use of said key directories (so I
can know it's e.g. graphite filling up, or /var/log filling up, or riak
filling up the disk
=> add directory space use monitoring

bin/riemann-rabbitmq
solves https://github.com/aphyr/riemann-tools/issues/101
=> Adding support for https connection

bin/riemann-varnish
Fixes #104.
Varnish 4+ changes the field names for Varnish statistics fields.
This change runs varnishstats -V (using popen3 because Varnish outputs
all version information to stderr and not stdout) and captures the
version via a regex.
A case statement switches on the version. A 4 or higher results in using
the new fields. Otherwise it defaults to the Varnish 3.x field names.
The command also had to change because the `-f` option no longer
supports a comma-separated list and now requires a glob or multiple
instantiations.
=> Added check and switch for Varnish 4

bin/riemann-dir-files-count, bin/riemann-dir-space
When setting :critical or :warning and using ruby 2.1, an "ArgumentError comparison of Fixnum with true failed" was obtained. These changes fix those errors.
=> Fixed failed comparison of Fixnum with True

bin/riemann-ntp
The collector uses ntpq to list the NTP peers.
It then returns the delay, offset and jitter for each to Riemann.
=> Added NTP statistics collector

bin/riemann-proc
means you can look at which processes matched in email/etc without having to ssh into the box.
=> riemann-proc alerts output which processes matched

bin/riemann-diskstats
Indeed, it refers to the `in_flight` field in diskstat file and is the only field that should/might go to zero. I think it's better to report the metric as it, without modification.
It might also be worth to rename the metric name.
Source :
- https://www.kernel.org/doc/Documentation/block/stat.txt
- https://www.kernel.org/doc/Documentation/iostats.txt
=> Change the way `ioreqs` metric is handled

bin/riemann-freeswitch
Added thread count for the Freeswitch process, which can be useful (was useful in my case :) ) to know when FS and its modules are requiring lots of OS threads.
thanks!
=> riemann-freeswitch sends number of threads used by Freeswitch

Rakefile.rb, bin/riemann-docker-health
Hi! 
I've created the docker-health tool that I was talking about in #119 
It works using the docker remote API and the `/container/_/stats` command (without stream).
Some open issues : 
* I could have made it _better_ using the "streaming" mode of the stats command, But this is out of my league in Ruby
* I could have made it run _faster_ using some parallel for-each instead of normal for-each
* The `host` that given for each container is determined by the host and container name (eg. `host-container`)
* No `load` option for this one, because the tick time is every 10 seconds, I think that it's alright, If people will want `load`, they can use riemann streams to mimic the behaviour
* The disk usage is still working using the code in `riemann-health` tool
* I've added dependency on …
=> Added docker-health tool

bin/riemann-marathon
Fetches metrics from /metrics endpoint in
[Marathon](https://mesosphere.github.io/marathon/) and pushes them to
riemann. This is derived from the elasticsearch watcher.
=> Add Marathon watcher

Rakefile.rb
I believe there's a typo in the dependency specification:
```
mareknowak@Mareks-MacBook-Pro: ~/stuff/riemann-tools master
$ rake gem                                                                   [12:44:39]
rake aborted!
Gem::Requirement::BadRequirementError: Illformed requirement ["=> 1.22.0"]
/Users/mareknowak/stuff/riemann-tools/Rakefile.rb:31:in `block in <top (required)>'
/Users/mareknowak/stuff/riemann-tools/Rakefile.rb:11:in `new'
/Users/mareknowak/stuff/riemann-tools/Rakefile.rb:11:in `<top (required)>'
(See full trace by running task with --trace)
FAIL: 1
mareknowak@Mareks-MacBook-Pro: ~/stuff/riemann-tools master
$ sed -i "" "s/=>/>=/g" Rakefile.rb                                          [12:44:49]
mareknowak@Mareks-MacBook-Pro: ~/stuff/riemann-tools master ⚡
$ rake gem …
```
=> Corrects a typo when specifying dependencies.

bin/riemann-consul
Currently it's a basic tool thats changes the status of a service registered to consul if all the health checks inside it are not "ok".
I hope that people that use consul and riemann would have some suggestions to add.
=> RFC : Riemann-consul : Sends consul services status to riemann

bin/riemann-mesos
This is derived from the Elasticsearch watcher. It simple fetches the
metrics from the [Mesos](http://mesos.apache.org) `/metrics/snapshot`
end-point and pushes them to the specified riemann instance.
=> Add Mesos metrics watcher

bin/riemann-elb-metrics
If no AWS keys are provided, use instance's profile.
=> Enable riemann-elb-metrics to use IAM Instance profile

bin/riemann-haproxy
Currently the server state is reported as state of each server metric. I think that this is wrong in two ways:
* Could be quite noisy - If the server goes down each of the server metrics will be sent as critical.
* This state is not relevant to the metric - The metric state should depend on thresholds (if such exist and can be defined at all). It does not make sense to send the same state everywhere.
Because of this I moved the server state in to separate event - "haproxy #{server} state".
=> Separate HAproxy's server state from server metrics

Rakefile.rb, tools/riemann-aws/Rakefile.rb, tools/riemann-docker/Rakefile.rb, tools/riemann-elasticsearch/Rakefile.rb, tools/riemann-marathon/Rakefile.rb, tools/riemann-mesos/Rakefile.rb, tools/riemann-munin/Rakefile.rb, tools/riemann-rabbitmq/Rakefile.rb, tools/riemann-riak/Rakefile.rb
1. Added license summary to gem build tasks
2. Added recursive build task to build all gems in tools/
3. Fixed gem links.
=> Updates to gems

lib/riemann/tools.rb
Previously if a tag is specified on the command line and a tag is
specified in a program then the command-line tag override the
program-specified tag.
This addresses that issue and merges the tags together.
=> Fixes #99 - Additive tags

bin/riemann-proc
Provides the following metrics for running processes:
- process/<pid>-<start-time>/rss
- process/<pid>-<start-time>/vsize
- process/<pid>-<start-time>/running
- process/<pid>-<start-time>/cputime
`description` should contain the command itself.
`state` is `ok` if running or sleeping, `warning` if idle and critical
if zombie or in interruptible wait.
`value` should be either process RSS, VSIZE, CPU TIME or 1 for the /running
case.
This also changes things so that:
- the metric for the number of processes matching will now be called
`count/<regex>`
- by default the regular expression for matching processes is `".*"` not
`""`.
- by default the minimum number of processes is set to 0
- by default the maximum number of processes is 32K
=> Improved riemann-proc

tools/riemann-elasticsearch/bin/riemann-elasticsearch
As I'd like to have some more insight into Elasticsearch during operations I added two metrics.
=> gather some simple metrics on query and fetch time

tools/riemann-elasticsearch/bin/riemann-elasticsearch
I did a mistake in the last PR, therefore the 0.2.0 of riemann-elasticsearch you tagged is not usable because it gives a ``NoMethodError undefined method `is_bad?'``.
=> correctly call is_bad? method

bin/riemann-health
I totally blanked on @df being inside the `initialize`. This should be a tick time execution of the command. As a result I've created a new method `df` to run the disk command when the `disk` method is executed rather than just when `riemann-health` starts.
=> Fixed issue with static disk monitoring

tools/riemann-docker/bin/riemann-docker
Apparently, getting container data from Docker may be slow (some of my requests to `/container/ID/stats` are longer than one second), and when you have a lot of containers running, events emitted from one container will expire before it gets enumerated again. 
Setting higher TTL looks and feels like a kludge; however, simultaneous requests to Docker API do not affect each other (much), so a simple solution is to make requests in parallel.
This small pull request does exactly that.
=> Make riemann-docker multithreaded

tools/riemann-aws/bin/riemann-elb-metrics
Hi, with this PR we fill empty datapoints for ELB metrics with zeroes (they have more value than "?" or "null").
Thanks! :+1:
=> Riemann Aws ELB: send 0 metric on empty result

bin/riemann-kvminstance
I had riemann-kvminstance reporting 0 all the time. I changed the line counting the instances.
Details:
The relevant line used to grep the virsh output:
```
kvm_instances = %x[virsh list |grep i-|wc -l]
```
which is reporting 0 on the internationalized version:
```
[root@ernie ~]# LANG=C virsh list
Id    Name                           State
----------------------------------------------------
7     db1.kr.naetverk.net            running
10    lb1.kr.naetverk.net            running
11    www1.kr.naetverk.net           running
[root@ernie ~]# 
```
I changed it to a working one, forcing C output and avoiding one pipe:
```
kvm_instances = %x[LANG=C virsh list | grep -c running]
```
=> Corrected kvm running instance count

Rakefile.rb
Reintroduces Ruby 1.9.3 compatibility,
JSON versions >= 2.0 require Ruby version >= 2.0
=> JSON dependency version set to ~> 1.8

bin/riemann-health
Both of these are based on the FreeBSD section that already existed. In fact I renamed freebsd_load to bsd_load because of reuse. I've used this on OpenBSD 5.9/Sparc64, OpenBSD 6.0/Sparc64, and an Illumos distribution, also on Sparc64. All of them using Ruby 2.3, though I don't think I used anything that isn't already used elsewhere so the Ruby version should be as constrained as prior.
=> Add OpenBSD and Illumos (sunos in uname -s) to riemann-health

Rakefile.rb
I'd be just as happy changing this to `>= 2.1' which is the current rubygems version, BTW
=> nudge json dependency to encompass 2.x

.docker/Dockerfile.tmpl, .docker/publish.sh, .travis.yml
This fixes #189
You will need to configure travis with the variables:
- `DOCKER_USER` your username on hub.docker.com
- `DOCKER_PASS` your password on hub.docker.com
- `IMAGE_PREFIX` (optional, default `riemannio/`) lets you store the images in a different namespace or private docker registry.
It will create multiple images. `riemann-tools` being the base binaries, like riemann-health. The additional tools are available as different images, for example `riemann-tools-docker` contains riemann-docker on top of the base binaries.
=> Implement automated docker builds of included tools.

.docker/Dockerfile, .docker/publish.sh
Initially I had planned on committing a single fat dockerfile that had all the tools and used that sed part to update gem the versions automatically. Now that it doesn't write files, it's easier to use `--build-arg`.
Also, for `--cache-from` you should manually call pull first. Forgotten about that.
=> Removed sed and fixed build caching.

bin/riemann-health
Alpine's `df` does not support `--exclude-type`.
This detect this using `--help`.
A small compose file to reproduce the issue with the current version:
```yml
version: '3.3'
services:
riemann-server:
image: riemannio/riemann
riemann-health:
image: riemannio/riemann-tools:0.2.14
command: riemann-health --host=riemann-server --checks=disk
```
Will output:
```
riemann-health_1  | df: unrecognized option: exclude-type=iso9660
riemann-health_1  | BusyBox v1.28.4 (2018-07-17 15:21:40 UTC) multi-call binary.
riemann-health_1  | 
riemann-health_1  | Usage: df [-PkmhTai] [-B SIZE] [FILESYSTEM]...
riemann-health_1  | 
riemann-health_1  | Print filesystem usage statistics
riemann-health_1  | 
riemann-health_1  | 	-P	POSIX output format
riemann-health_1  | 	-k	1024-byte blocks (default) …
```
=> Fix df --exclude-type on alpine

bin/riemann-health
Running "df" on NFS mounts may incur high latency and delay all other metrics, resulting in false alerts.
=> Exclude NFS from df

Rakefile.rb, lib/riemann/tools.rb
With https://github.com/riemann/riemann-ruby-client/pull/33 in the _riemann-client_ gem, we can bring support for TLS to _riemann-tools_!
Fixes #142
=> Add support for TLS

.github/workflows/ci.yml, .rspec, bin/riemann-health, lib/riemann/tools/utils.rb, riemann-tools.gemspec, spec/riemann/tools/utils_spec.rb, spec/spec_helper.rb
When listing processes to fill-in the description of CPU and memory
events, the first line of the output from ps(1) is mixed with the rest
of the output which list processes which can result in weird reports
where the header line is mixed with the rest of the output:
```
root@theremin ~ # ps -eo pcpu,pid,comm | sort -nrb -k1 | head -10
3.2    2216 corosync
1.1    2268 pvestatd
%CPU     PID COMMAND
0.4  460190 fail2ban-server
0.4    2266 pve-firewall
0.3    2857 systemd
0.3    2386 systemd
0.3    1089 z_rd_int_1
0.3    1088 z_rd_int_0
0.2    2138 pmxcfs
```
Add a utility function for sorting lines by reverse numeric value while
keeping the header line untouched.
While here, introduce some CI with GitHub actions.
=> Fix cpu and memory usage sorting

CHANGELOG.md, Rakefile, lib/riemann/tools/version.rb, riemann-tools.gemspec
Following riemann-ruby-client 1.0.0 release, do a 1.0.0 release for riemann-tools :tada:
=> Release 1.0.0

lib/riemann/tools/health.rb
When the disk facts where refactored, we introduced a regression that
cause tmpfs disks to be reported while they where not previously.
Add tmpfs to the default ignore list to revert to the previous behavior.
=> Revert tmpfs as an ignored filesystem by default

lib/riemann/tools/health.rb
In the Linux world, filesystem overlays allows to mount a directory on
top of another directory.  Because we already collect usage information
for the filesystems that contain the "lower" layer, we do not need to
collect information about the "upper" layer which dupplicate the same
information.
This helps avoiding transcient data about short-lived filesystems
created e.g. by CI systems that rely on Docker.
=> Ignore overlay filesystems by default

.github/workflows/ci.yml, .gitignore, .rubocop.yml, Rakefile, lib/riemann/tools/health.rb, lib/riemann/tools/uptime_parser.y, riemann-tools.gemspec, spec/riemann/tools/uptime_parser_spec.rb
Make a new metric with the node uptime available.  The metric is the raw uptime in seconds and the description is a human readable duration.  Critical and Warning thresholds are reversed when compared to other metrics: a value lower that these thresholds indicates a problem. This is intended to get notifications when nodes restart unexpectedly.
The uptime check is not enabled by default and must be explicitly enabled using the `--checks` flag.
=> Add uptime monitoring to riemann-health

lib/riemann/tools/health.rb, spec/riemann/tools/health_spec.rb
Rely on `swapinfo(1)` on all OS excepted from Linux which does not have this UNIX utility but provide an entry in /proc that reports swap usage.
Enable it by default.
=> Add swap reporting to riemann-health

lib/riemann/tools/health.rb
squashfs is a compressed read-only filesystem, always reported as full,
so we should exclude it by default.
=> Ignore squashfs from disks usage reporting

bin/riemann-freeswitch, bin/riemann-kvminstance, bin/riemann-wrapper, lib/riemann/tools.rb, lib/riemann/tools/apache_status.rb, lib/riemann/tools/cloudant.rb, lib/riemann/tools/consul_health.rb, lib/riemann/tools/freeswitch.rb, lib/riemann/tools/haproxy.rb, lib/riemann/tools/kvm.rb, lib/riemann/tools/nginx_status.rb, lib/riemann/tools/riemann_client_wrapper.rb, tools/riemann-aws/bin/riemann-aws-billing, tools/riemann-aws/bin/riemann-aws-rds-status, tools/riemann-aws/bin/riemann-aws-sqs-status, tools/riemann-aws/bin/riemann-aws-status, tools/riemann-aws/bin/riemann-elb-metrics, tools/riemann-aws/bin/riemann-s3-list, tools/riemann-aws/bin/riemann-s3-status, tools/riemann-aws/lib/riemann/tools/aws/billing.rb, tools/riemann-aws/lib/riemann/tools/aws/elb_metrics.rb, tools/riemann-aws/lib/riemann/tools/aws/rds_status.rb, tools/riemann-aws/lib/riemann/tools/aws/s3_list.rb, tools/riemann-aws/lib/riemann/tools/aws/s3_status.rb, tools/riemann-aws/lib/riemann/tools/aws/sqs_status.rb, tools/riemann-aws/lib/riemann/tools/aws/status.rb, tools/riemann-riak/lib/riemann/tools/riak.rb
A Ruby process has an entry memory cost of about 15 Mb in resident memory
size (RSS).  This is for a process that does nothing and wait for input
on stdin.  When running actual code, this grows with each file loading
and object creation.
Currently, a single riemann-tool process consume about 30 Mb of RSS.
When multiple tools are running simultaneously, these RSS sizes sum up.
Add a generic wrapper tool that allows to run multiple tools from a
single Ruby process, reducing the memory footprint required for the same
workload.
```
bundle exec bin/riemann-diskstats &
bundle exec bin/riemann-fd &
bundle exec bin/riemann-health &
bundle exec bin/riemann-net &
bundle exec bin/riemann-ntp &
bundle exec bin/riemann-proc &
```
Relevant ps(1) output:
```
F   UID     PID    PPID PRI  NI    VSZ   RSS …
```
=> Add a wrapper to run multiple tools in a single process

bin/riemann-freeswitch, bin/riemann-kvminstance, lib/riemann/tools/freeswitch.rb, lib/riemann/tools/kvm.rb, tools/riemann-aws/bin/riemann-aws-billing, tools/riemann-aws/bin/riemann-aws-rds-status, tools/riemann-aws/bin/riemann-aws-sqs-status, tools/riemann-aws/bin/riemann-aws-status, tools/riemann-aws/bin/riemann-elb-metrics, tools/riemann-aws/bin/riemann-s3-list, tools/riemann-aws/bin/riemann-s3-status, tools/riemann-aws/lib/riemann/tools/aws/billing.rb, tools/riemann-aws/lib/riemann/tools/aws/elb_metrics.rb, tools/riemann-aws/lib/riemann/tools/aws/rds_status.rb, tools/riemann-aws/lib/riemann/tools/aws/s3_list.rb, tools/riemann-aws/lib/riemann/tools/aws/s3_status.rb, tools/riemann-aws/lib/riemann/tools/aws/sqs_status.rb, tools/riemann-aws/lib/riemann/tools/aws/status.rb
Improve the way class and filenames are matched.  The idea is to be able
to automatically require files based on the requested class name using
methods like Rails' String#underscore / String#camelize methods.
This will help with the creation of a generic wrapper abble to load
dynamically extra tools which are unknown to the base riemann-tool gem.
While here, spot and fix a few naming mistakes in previous commit.
=> Normalize class names

lib/riemann/tools/health.rb
Default to low thresholds because we don't expect users to be signed-in on servers, but this can be tuned the usual way with some flags.
For now, this check is not enabled by default (see #227 for a discussion about this).
=> Add users monitoring to riemann-health

CHANGELOG.md, Rakefile, lib/riemann/tools/version.rb
While here, fix how gem tags are formatted by the Ruby ecosystem.
=> Bump version to 1.2.0

bin/riemann-zpool, lib/riemann/tools/zpool.rb, spec/riemann/tools/zpool_spec.rb
Introduce riemann-zpool, a simple wrapper around `zpool status` that
reports the system's pools health.
=> Add `riemann-zpool` to monitor zpool health

.gitignore, .rubocop.yml, Rakefile, bin/riemann-md, lib/riemann/tools/md.rb, lib/riemann/tools/mdstat_parser.y, riemann-tools.gemspec, spec/fixtures/mdstat/example-1, spec/fixtures/mdstat/example-10, spec/fixtures/mdstat/example-11, spec/fixtures/mdstat/example-2, spec/fixtures/mdstat/example-3, spec/fixtures/mdstat/example-4, spec/fixtures/mdstat/example-5, spec/fixtures/mdstat/example-6, spec/fixtures/mdstat/example-7, spec/fixtures/mdstat/example-8, spec/fixtures/mdstat/example-9, spec/riemann/tools/md_spec.rb, spec/riemann/tools/mdstat_parser_spec.rb
The Linux kernel expose the status of md devices as a file /proc/mdstat
that has quite dynamic content.  Implement a parser to gather the
relevant information and report the system md devices health.
=> Add `riemann-md` to monitor Linux RAID/md health

bin/riemann-wrapper
We need to pass the created tool instance to the thread we create as a
parameter, otherwise the thread get the tool from the parent scope where
the variable can have been replaced by another tools.
Old behavior:
[main] instance <- tool1
[main] start thread1
[main] instance <- tool2
[main] start thread2
[thread1] use instance from main (i.e. tool2)
[thread2] use instance from main (i.e. tool2)
New behavior:
[main] instance <- tool1
[main] start thread1 passing instance from main (i.e. tool1)
[main] instance <- tool2
[main] start thread2 passing instance from main (i.e. tool2)
[thread1] use instance from thread1 (i.e. tool1)
[thread2] use instance from thread2 (i.e. tool2)
Fixes #230
=> Fix race condition in riemann-wrapper

bin/riemann-wrapper
If a single argument is passed to riemann-wrapper, assume it is a
configuration file and build ARGV by reading its content.
This is backward compatible with the existing argument parsing and makes
it ealier to run a set of tools with custom configuration for
development or when managing riemann-wrapper config with configuration
management.
=> Add support for configuration file to riemann-wrapper

bin/riemann-wrapper
The default behavior of Ruby when an exception is raised in a thread is
to not re-raise this exception in the main thread.  When using
`riemann-wrapper` to run multiple tools, if a tool raise an error, that
tool will stop functionning but the other tools will continue to operate
normally, which might lead to unexpectedly expired services hard to
diagnose because the monitoring service is still running.
The tools are expected to gracefuly handle exceptions, but… sh*t
happens.
As a safety, set `Thread.abort_on_exception` to true so that if any
thread is aborted by an exception, the raised exception will be
re-raised in the main thread.  Because we do not catch such exceptions
in `riemann-wrapper`, the process will terminate, and the parent process
(e.g. systemd) will hopefuly re-start it.
=> Stop riemann-wrapper if a tool raise an error

lib/riemann/tools/zpool.rb, spec/fixtures/zpool/degraded, spec/fixtures/zpool/healthy, spec/riemann/tools/zpool_spec.rb
The exit status from `zpool status -x` cannot be used to detect if a
pool is degraded.  Scan the output instead.
=> Fix detection of degraded zpool

lib/riemann/tools/md.rb, lib/riemann/tools/zpool.rb, spec/fixtures/zpool/degraded, spec/fixtures/zpool/healthy, spec/riemann/tools/md_spec.rb, spec/riemann/tools/zpool_spec.rb
Informational messages are reported as `description`, not `message`.
This PR also include:
* #237
=> Fix zpool/md informational messages reporting

lib/riemann/tools/md.rb, lib/riemann/tools/zpool.rb, spec/fixtures/zpool/cksum, spec/fixtures/zpool/degraded, spec/fixtures/zpool/faulted, spec/fixtures/zpool/healthy, spec/fixtures/zpool/resilvering, spec/riemann/tools/md_spec.rb, spec/riemann/tools/zpool_spec.rb
When a FAULTED or DEGRADED zpool is back ONLINE and resilvering after changing disks, it is still reported in `zpool status -x` output until the pool is healthy again.  Such a state should probably not be reported as critical but it is still something to keep an eye on, so report all the known-bad states as `critial` as before but report this resilvering status (and also unknown statuses that might be introduced in the future) as `warning` only.
This PR also include:
* #237
* #238
=> Improve zpool state reporting

CHANGELOG.md, lib/riemann/tools/version.rb
Reporting a degraded zpool as 'ok' is quite critical, so let's quickly release a fix!
=> Bump version to 1.4.0

lib/riemann/tools/mdstat_parser.y, spec/fixtures/mdstat/example-12, spec/riemann/tools/mdstat_parser_spec.rb
The content of /dev/mdstat when a device is being checked looks like the
one of a device being recovering, and [a few more values can be
reported](https://github.com/torvalds/linux/blob/7726d4c3e60bfe206738894267414a5f10510f1a/drivers/md/md.c#L8089-L8098).
This information is reported *before* the bitmap when present, and not
after as the parser expected (the examples from the documentation did
not mix bitmaps and recovery, but the weekly check from Debian broke the
`mdstat` reporting during the check).
Fix the ordering and allow the new values to be parsed.  Add an example
from a live output of one of our nodes to ensure we don't break this in
the future.
=> Fix parsing of mdstat when device is being checked

lib/riemann/tools/haproxy.rb
Fixes the following error returned by `riemann-haproxy`:
```
NoMethodError undefined method `body' for #<Net::HTTP haproxy_host:8404 open=false>
```
=> Fix `riemann-haproxy` HTTP response processing

lib/riemann/tools/health.rb, lib/riemann/tools/md.rb, lib/riemann/tools/mdstat_parser.y, lib/riemann/tools/uptime_parser.y, lib/riemann/tools/utils.rb, spec/riemann/tools/health_spec.rb, spec/riemann/tools/md_spec.rb
When a parser cannot parse a document, it raised a Racc::ParseError if
the document was malformed or a RuntimeError if the content was not
processable.  In any case, the exception was not explicitely catched and
was logged to stderr.  If events where previously reported they would
eventualy expire, otherwise nothing would make the failure visible on the
riemann side.
Improve exception handling by formatting a custom error messages which
show the line of the failure in the parsed document and sending it as a
critical event to riemann.
=> Improve error reporting on parse error

lib/riemann/tools/health.rb, spec/riemann/tools/health_spec.rb
GNU df(1) can localize its output.  This breaks riemann-health header
detection.
Because the header is always on the first line, we can ignore this line and do
not care about its content.
Add a unit test that shows the problem so that we can fix
it and not break it in the future.
=> Fix `riemann-health` detection of `df` header

.github/workflows/ci.yml, README.markdown, bin/riemann-http-check, lib/riemann/tools/http_check.rb, riemann-tools.gemspec, spec/riemann/tools/http_check_spec.rb
riemann-tools feature `riemann-portcheck` which can check if a port can be reached, but this is intended to check local services only and does not communicate over the connected socket, so can't detect some failure conditions like bad gateways.
Add a `riemann-http-check` that accept a list of URI of resources to check using HTTP(S) GET requests. For each URI, resolve the IP addresses that provide the service, and for each IP address generate 3 events: *connection latency*, *response latency* and *response code*. Then generate a last *consistency* event.
1. *connection latency* is a duration in seconds, the warning and critical threshold are respectively 100ms and 250ms, they can be tuned with the `--connection-latency-warning` and `--connection-latency-critical flags`;
2. *response …
=> Add `riemann-http-check` to monitor HTTP(S) resources

lib/riemann/tools/md.rb, spec/riemann/tools/md_spec.rb
Now that we report each device independently, we can add filtering
capabilities to help monitoring Enterprise(R)(TM) Products with dubious
RAID configuration (I am looking at you Synology).
This PR also include:
- #251
=> Allow mdstat device filtering

lib/riemann/tools/md.rb, spec/riemann/tools/md_spec.rb
Instead of a single `mdstat` event reporting the global health status of
all md devices, generate one event per device.
=> Report mdstat health by device

lib/riemann/tools/diskstats.rb, lib/riemann/tools/http_check.rb, spec/riemann/tools/http_check_spec.rb, spec/spec_helper.rb
IP addresses resolution and HTTP resources fetching are I/O bound. When testing a large amount of HTTP endpoints, this can be an issue.  Some measurement we did for a use case show that checking 112 URI (most of them being serviced by 2 IP addresses) took 95 seconds.
Implement an address resolution queue and a working queue in order to parallelize tasks in multiple threads.  With a default of 5 resolvers and 20 workers, our test case now completes in about 4 seconds, which is more than 23 times faster.  These values can be tuned using the --resolvers and --workers new parameters.
While here, add metrics to track the resolvers and workers utilization and saturation.
=> Speed-up `riemann-http-check` with resolver and worker threads

lib/riemann/tools/http_check.rb
By setting the warning and critical thresholds of the latency checks to
0, allow the metrics to be generated but do not attach a state to them.
This allows monitoring sites where connectivity is unreliable and we do
not really care about alerting when routing change and we suddently need
10 more seconds to reach the other side of the world.
=> Allow opting out of `riemann-http-check` latency state

.github/workflows/ci.yml, lib/riemann/tools/http_check.rb
When the host part of an URI cannot be resolved, the `riemann-http-check` assume it is an IP address and attempt to parse it. But when this host is not an IP address, a `IPAddr::InvalidAddressError` exception is raised and is not catch, no metric is emitted, and the thread that raised the exception terminate.  On next attempt, another thread is killed, and soon no more resolver thread is available for the system to function properly.
Catch the `IPAddr::InvalidAddressError` exception and ignore it.  When the name is not resolvable, this produce a consistency metric with the critical state because no response can be collected for the URI.
=> Fix `riemann-http-check` with unresolvable domains

lib/riemann/tools/apache_status.rb, lib/riemann/tools/cloudant.rb, lib/riemann/tools/consul_health.rb, lib/riemann/tools/haproxy.rb, lib/riemann/tools/http_check.rb, lib/riemann/tools/nginx_status.rb, tools/riemann-riak/lib/riemann/tools/riak.rb
The default User-Agent for Net::HTTP is "Ruby".
In order to make it easier to distinguish traffic from various sources, change this default User-Agent string with a custom one based on the riemann tool name and version, and also include the project URL in the same way bots report their URL.
=> Override default HTTP User-Agent and make it tuneable

lib/riemann/tools/apache_status.rb, lib/riemann/tools/cloudant.rb, lib/riemann/tools/consul_health.rb, lib/riemann/tools/haproxy.rb, lib/riemann/tools/http_check.rb, lib/riemann/tools/nginx_status.rb, tools/riemann-riak/lib/riemann/tools/riak.rb
When running the tools via bundler, `riemann/tools/version` is loaded and `Riemann::Tools::VERSION` is defined.  But when running as a gem, it is not loaded leading to an error at startup.
Explicitly require the version in the files that use it.
=> Fix uninitialized constant Riemann::Tools::VERSION (NameError)

lib/riemann/tools/riemann_client_wrapper.rb, riemann-tools.gemspec
Sending an event to riemann can take some time. If during this time multiple events are generated, they will stack and be send one by one instead of being transmitted in bulk.
We added a new API function to riemann-client to send events in bulk:
* https://github.com/riemann/riemann-ruby-client/pull/44
Add a send queue and a worker thread that will send events in bulk if more than one is ready to be sent.
This is being tested ATM, the PR will be updated when we have collected enough data
=> Send events in bulk when they are stacking

lib/riemann/tools.rb, lib/riemann/tools/riemann_client_wrapper.rb, spec/riemann/tools/riemann_client_wrapper_spec.rb
Now that we do not send events from the main thread, we must take care
to wait for events to be send when the main thread is about to exit.
When a short-lived riemann tool queue events for delivery and exit, this
will allow these events to be delivered.
=> Make sure all events are send before terminating

lib/riemann/tools/riemann_client_wrapper.rb
This PR add a bunch of enhancements to the event sender thread to make the system more resilient to transcient communication errors.
When riemann was unreachable, `riemann-wrapper` was terminating, and the other tools stopped trying to send events (even if riemann was reachable again).  This is now fixed by logging the failure and droping the events.  Other (unknown) errors in the event sending thread now cause a termination of the program in all cases, with some diagnostic messages.
=> Improve event sending thread lifecycle management

lib/riemann/tools/riemann_client_wrapper.rb
We detect Riemann communication errors and in such circumstances, drop events and continue processing operations in order to cope with transient communication failures.
Some network errors raise generic `SocketError` exceptions, `OpenSSL::SSL::SSLError` or `EOFError` exceptions.  Such errors should likewise also be ignored instead of causing the program termination.
=> Gracefully handle all communication errors

lib/riemann/tools/riemann_client_wrapper.rb
When the communication with the Riemann server is connected (TCP/TLS) and the link breaks, riemann-wrapper drop the events that failed to be send, log a warning, and immediately try to reconnect and proceed with remaining data.
When the Riemann server is unreachable because of some network connectivity issue, this new connection will likely immediately fail, freshly gathered events will be dropped, a new warning will be logged, and a new connection will be tried immediately.
Because we do not wait before reconnecting, we log an unexpectedly large amount of information about dropped messages, and because of the delays introduced by the reconnection attempts, we might be sending stale data when the connection succeed again.
Rework the disconnection detection logic to apply some truncated …
=> Use truncated exponential backoff for reconnection

lib/riemann/tools.rb, lib/riemann/tools/bench.rb, lib/riemann/tools/haproxy.rb, lib/riemann/tools/net.rb, spec/riemann/tools/haproxy_spec.rb
Ruby 3.0 and newer does not like passing a Hash in place of Keyword Arguments.
More info:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
Ensure we use a working syntax with all versions of Ruby supported by the gem.
=> Fix `riemann-haproxy` with Ruby 3.0+

lib/riemann/tools/haproxy.rb
Previous refactoring was intended to make the code testable to unbreak
it, but a copy/paste error in the non-tested code path was introduced
causing an exception at runtime:
```
NoMethodError undefined method `body' for nil:NilClass
```
Move the line at the right position where `res` is available.
=> Fix `riemann-haproxy` NoMethodError

bin/riemann-wrapper
When `riemann-wrapper` is used with a configuration file (and only in
this case), it is not possible to prevent splitting of options
containing spaces, adding an arbitrary constraint for the user if they
want to pass options with spaces (e.g. when passing a custom format
string to a tool).
Rework options splitting when reading options from a file, so that the
user can:
* quote part of the string (i.e. `options: --format='foo bar'`);
* escape spaces (i.e. `options: --format=foo\ bar`).
The above examples are evaluated as an array with a single string item:
`["--format=foo bar"]`.
=> Add support for options with spaces to `riemann-wrapper`

.rubocop.yml, Gemfile, Rakefile, bin/riemann-wrapper, lib/riemann/tools.rb, lib/riemann/tools/bench.rb, lib/riemann/tools/diskstats.rb, lib/riemann/tools/health.rb, lib/riemann/tools/http_check.rb, lib/riemann/tools/net.rb, lib/riemann/tools/nginx_status.rb, riemann-tools.gemspec, spec/riemann/tools/haproxy_spec.rb, spec/riemann/tools/health_spec.rb, spec/riemann/tools/http_check_spec.rb, spec/riemann/tools/md_spec.rb, spec/riemann/tools/net_spec.rb, spec/riemann/tools/utils_spec.rb, spec/riemann/tools/zpool_spec.rb, tools/riemann-aws/lib/riemann/tools/aws/s3_status.rb, tools/riemann-aws/lib/riemann/tools/aws/status.rb, tools/riemann-docker/lib/riemann/tools/docker.rb, tools/riemann-riak/lib/riemann/tools/riak.rb
Rubocop is not configured to detect and help fixing all issues it can spot.  Enable this code to improve further the code of the gem.
Also include:
* #283 
* #284
=> Enable the `rubocop-rake` and `rubocop-rspec` gems

Gemfile, spec/riemann/tools/http_check_spec.rb
The project dependencies now allow rack 3 to be installed.  This backwards incompatible version extracted handlers in a new `rackup` gem.  While we could indicate we prefer to use rack 2 which is still receiving update, it is more future-proof to update our code to be compatible with the latest version of the dependency.
This is a development dependency only so will not affect users of the project.
=> Allow using the latest version of rack (3.x)

Gemfile, lib/riemann/tools/http_check.rb, spec/riemann/tools/http_check_spec.rb
Under normal operation, we have a single instance of the `Riemann::Tools::HttpCheck` class for the lifetime of the monitoring process.
But when testing, we create a new instance for each test, each with its resolvers and worker thread pools.  The test process will have more and more threads, until it eventually hit the OS limit of the maximum number of threads for a process and cause an exception:
> ThreadError: can't create Thread: Resource temporarily unavailable
Make sure that the threads are terminated at the end of each test to avoid running out of resources if they are limited.
Also include:
* #283
=> Terminate `Riemann::Tools::HttpCheck` threads between tests

lib/riemann/tools/health.rb, spec/riemann/tools/health_spec.rb
Disk thresholds as a fraction of their usage does not scale well with
modern disks: on one hand a 90% full partition that store logs is
generaly an issue and should be reported, but in the other hand when a huge
volume is available for storing backups (e.g. 10TB) the 90% usage limit
does not really make sense as we do not want to waste 1TB of disk space.
Introduce two new parameters to tune disk usage thresholds:
- `--disk-warning-leninency` (default: 500G)
- `--disk-critical-leninency` (default: 250G)
When the fraction of disk space used reach a warning / critical
threshold, check the available space against these "leninency" values,
and only report the warning / critical status if the available space is
lower than this limit.
The defaults values have been chosen to be high enough to …
=> Add leniency to disk thresholds of `riemann-health`

lib/riemann/tools/health.rb, lib/riemann/tools/http_check.rb, spec/riemann/tools/health_spec.rb, tools/riemann-docker/lib/riemann/tools/docker.rb
On Linux, memory used by the ZFS ARC is reported as used while in fact
it mostly consist of cached data that can be reclaimed by the operating
system if necessary.
If the system use ZFS, gather the ARC statistics to compute the size
of the ARC that can be evicted and do not count this as used memory.
This fix the obviously wrong reporting we can see on systems running
ZFS.
Containers running on nodes with ZFS can access the hosts ARC
statistics from the container, resulting in wrong memory reporting.  To
avoid this, we detect if we are running from a container and skip
reading the ARC statistics in that case.
=> Fix `riemann-health` memory reporting when using ZFS on Linux

bin/riemann-wrapper
This reverts commit b4254bdb13658a9f65b1d1ee2efa1e7cbf1d834c.
The YAML.safe_load_file function was added in Psych 3.2.1, but only Ruby
3 and newer provide this version of the Psych library.  Since this gem
is supposed to work with older (EOL) Ruby versions, revert this for now.
At some point we will drop support for EOL Ruby, but it will be a
backwards incompatbile change and there is no hurry for that at the
moment, and some supported Linux distro still ship these legacy Ruby
versions.
=> Fix `riemann-wrapper` with older Ruby

tools/riemann-aws/lib/riemann/tools/aws/billing.rb, tools/riemann-aws/lib/riemann/tools/aws/status.rb, tools/riemann-rabbitmq/lib/riemann/tools/rabbitmq.rb
`#opts` is an alias for `#options` in the `Riemann::Tools` class.
While most of the tools use `#opts`, a few ones une `#options`, but the
files in this commit use both functions, which can cause confusion.
To avoid this, stick to `#opts`.  Files that consitently use `#options`
are kept as is.
No functional change.
=> Fix mixing `#opts` and `#options`

lib/riemann/tools/nginx_status.rb
The `riemann-nginx` tool accept a `--checks` parameter since it was
introduced in #33, but this parameter was never used to filter events.
Make sure we only return events that match the provided checks.
=> Fix `riemann-nginx` checks selection

lib/riemann/tools.rb, lib/riemann/tools/apache_status.rb, lib/riemann/tools/bench.rb, lib/riemann/tools/consul_health.rb, lib/riemann/tools/dir_files_count.rb, lib/riemann/tools/dir_space.rb, lib/riemann/tools/diskstats.rb, lib/riemann/tools/fd.rb, lib/riemann/tools/freeswitch.rb, lib/riemann/tools/haproxy.rb, lib/riemann/tools/health.rb, lib/riemann/tools/http_check.rb, lib/riemann/tools/net.rb, lib/riemann/tools/nginx_status.rb, lib/riemann/tools/ntp.rb, lib/riemann/tools/portcheck.rb, lib/riemann/tools/proc.rb, lib/riemann/tools/varnish.rb, tools/riemann-aws/lib/riemann/tools/aws/billing.rb, tools/riemann-aws/lib/riemann/tools/aws/rds_status.rb, tools/riemann-aws/lib/riemann/tools/aws/sqs_status.rb, tools/riemann-aws/lib/riemann/tools/aws/status.rb, tools/riemann-chronos/lib/riemann/tools/chronos.rb, tools/riemann-docker/lib/riemann/tools/docker.rb, tools/riemann-marathon/lib/riemann/tools/marathon.rb, tools/riemann-munin/lib/riemann/tools/munin.rb, tools/riemann-riak/lib/riemann/tools/riak.rb
When a tool is run with stray arguments, they are silently ignored. This typically happen when a parameter must be repeated for each value (e.g. the `--tag` parameter is passed multiple values with `--tag foo --tag bar` and passing `--tag foo bar` only provide a single tag and the `bar` value is an argument that is silently ignored).
In order to avoid this issue, raise an error by default if stray arguments are found.  It is possible to indicate that stray arguments are allowed by expilcitly saying so.  In this case, the arguments are accessible using the `#argv` method.
=> Detect and report stray arguments

bin/riemann-hwmon, lib/riemann/tools/hwmon.rb, spec/riemann/tools/http_check_spec.rb, spec/riemann/tools/hwmon/device_spec.rb
hwmon is a Linux interface to access harware monitors such as the temperature of devices, input voltage, and so on.
This tool rely on the files exposed by the sysfs filesystem.
=> Add a new `riemann-hwmon` tool for harware monitors

spec/riemann/tools/http_check_spec.rb
Older versions provided backwards compatibility, but with the new major version of rack, this has gone away.
This fix CI with recent versions or Ruby.  Until this is merged, PRs will be on top of this branch.
=> Fix CI with latest Rack

lib/riemann/tools/hwmon.rb
- Improve `riemann-hwmon` reliability
- Avoid trailing space when sensor has no label
=> Minor `riemann-hwmon` improvements

lib/riemann/tools.rb, spec/riemann/tools_spec.rb
When running with riemann-wrappers, one may want to run different tools with distinct ttl, but the `--ttl` flag cannot be specified twice, so the following configuration where we want to run the `health` tool every 5 seconds (default value) but with a longer TTL than the default (twice the interval) will **not** work:
```yaml
---
options: --ttl 300
tools:
- name: "health"
- name: "rdap"
options: "--interval 21600 --ttl 86400 --domains example.com example.net"
```
A workaround is to add an explicit ttl for each tool, but it is not convenient.
Introduce a `--minimum-ttl` flag that can be used as a global option to circumvent this issue:
```yaml
---
options: --minimum-ttl 300
tools:
- name: "health"
- name: "rdap"
options: "--interval 21600 --ttl 86400 --domains example.com example.net"
```
=> Add support for a minimum TTL for events

bin/riemann-tls-check, lib/riemann/tools.rb, lib/riemann/tools/http_check.rb, lib/riemann/tools/tls_check.rb, lib/riemann/tools/utils.rb, spec/riemann/tools/tls_check/tls_check_result_spec.rb, spec/riemann/tools/tls_check_spec.rb
Add a `riemann-tls-check` that accept a list of URI of resources to check TLS certificates.
For each URI, resolve the IP addresses that provide the service, and for each IP address perform a TLS handshake and generate events from the certificate:
1. availability: :ok:/:boom: global status of all the following metrics + reachability;
2. not after: :ok:/:boom: + :chart_with_downwards_trend: number of seconds until the certificate is expired;
3. not before: :ok:/:boom: + :chart_with_upwards_trend: number of seconds since the certificate is valid;
4. identity: :ok:/:boom: certificate subject match the URI hostname;
5. trust: :ok:/:boom: validity of the certificate trust chain;
6. OCSP satus: :ok:/:boom: validity of the OCSP status if applicable.
(icons legend: :ok:/:boom: => the metric report …
=> Add `riemann-tls-check` to monitor TLS certificates

lib/riemann/tools/bench.rb, lib/riemann/tools/tls_check.rb, riemann-tools.gemspec, spec/riemann/tools/http_check_spec.rb
Unlike other clients, riemann-bench only support a connection to riemann
using default parameters and has no way to tune it.
Use the same pattern as used in other tools so that we have a unified
command line interface accross tools.
=> Improve riemann-bench

.github/workflows/ci.yml, Gemfile, riemann-tools.gemspec, spec/riemann/tools/http_check_spec.rb
Ruby 2.6 reached EOL on March 31, 2022.
Maintaining support of legacy versions of Ruby require time we can
better use for other projects, and make it harder for us to make sure
the project works correctly with up-to-date dependencies.
We are therefore dorpping support for this version of Ruby.
=> Drop support for Ruby < 2.7

lib/riemann/tools/health.rb, lib/riemann/tools/hwmon.rb, spec/riemann/tools/hwmon/device_spec.rb, tools/riemann-rabbitmq/lib/riemann/tools/rabbitmq.rb
When multiple identical i2c devices are present on a host (typical case for temperature sensors on memory modules), they overwrite each other metrics making monitoring unreliable.
Detect if the hwmon sensor is queried over i2c and if so add location information so that each device is reported with a different service.
Also include:
- #303
- #304
=> Distinguish i2c devices in `riemann-hwmon`

lib/riemann/tools/hwmon.rb, tools/riemann-rabbitmq/lib/riemann/tools/rabbitmq.rb
After updating some nodes of our infra, we stated to see this error
filling the logs:
```
Errno::ENODATA No data available @ io_fread - /sys/class/hwmon/hwmon4/temp1_input
+12 lines of backtrace
```
Indeed, the sensor system seems somewhat broken:
```
root@xylophone ~ # cat /sys/class/hwmon/hwmon4/temp1_input
cat: /sys/class/hwmon/hwmon4/temp1_input: No data available
root@xylophone ~ # echo $?
1
```
Catch such exception and ignore it as there is nothing better we can do
for now.
=> Ignore invalid data in `riemann-hwmon`

lib/riemann/tools/health.rb, lib/riemann/tools/hwmon.rb, tools/riemann-rabbitmq/lib/riemann/tools/rabbitmq.rb
`efivarfs` is a new type of filesystem to replace `sysfs` for
maintaining EFI variables.  It does not make sense to monitor it and
report its usage so add it to the default ignore list.
=> Ignore `efivarfs` disks in `riemann-health` checks
